### ISSUE TITLE
Unable to install buildfire npm module

### ISSUE THREAD

**Issue by grassynull33** [BuildFire/sdk-cli#3]
I tried finding a solution online, but it seems there is an issue with the buildfire-cli npm package. Whenever I try to globally install it using the command "npm install buildfire -g", I get the following error:

`404 Not Found: buildfire@latest`

The reason I am attempting to install this npm package is to develop a custom webpack plugin using this template here ([https://github.com/BuildFire/plugin-template-webpack](https://github.com/BuildFire/plugin-template-webpack)). Without the buildfire cli commands, I have not figured out how to build properly. A lot of the newer plugin repos on GitHub have instructions that require the buildfire cli commands in order to proceed.

If you have any insight or workarounds, please let me know. And if you need any more information from me, I will get back to you shortly.

Here is the log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.9.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'buildfire',
1 verbose cli   '-g' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose npm-session 580e85987c47a911
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/buildfire 1194ms
8 silly fetchPackageMetaData error for buildfire@latest 404 Not Found: buildfire@latest
9 verbose stack Error: 404 Not Found: buildfire@latest
9 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:789:20)
9 verbose stack     at tryOnImmediate (timers.js:751:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
10 verbose cwd /Users/yoonlee/Dropbox/imge/development/sdk/plugins/placesPlugin2
11 verbose Darwin 17.2.0
12 verbose argv "/usr/local/Cellar/node/8.9.1/bin/node" "/usr/local/bin/npm" "install" "buildfire" "-g"
13 verbose node v8.9.1
14 verbose npm  v5.5.1
15 error code E404
16 error 404 Not Found: buildfire@latest
17 verbose exit [ 1, true ]
```

**Comment by abuturla** [comment]
@yoonslee The latest changes to the SDK-CLI haven't been published to NPM yet, so you won't be able to utilize it until then. 

For now you can use the following steps:

1. If you haven't already, clone the BuildFire SDK.
2. In the SDK's plugins folder, clone the Webpack template repo.
3. Remove the .git file from the template repo.
4. Rename the template folder to match the name of your new plugin.
5. From within your new plugin folder, run `npm install`.
6. From the same folder run `npm start`.
7. Run the SDK as you normally would.

**Comment by DanielHindi** [comment]
due to inactivity
